
public class IntroPane {
 //This will add the CODERBOY PRESENTS PICTURE ONA TIMER BASIS AND THE INSTRUCTIONS AFTERWARDS
	// DO THIS LAST BECAUSE OTHERWISE IT WILL BE TOO LONG TO TEST THE GAME EVERYTIME
}
